component: scf
name: SwiftBenchmarkDemo
inputs:
  name: benchmark-swift-scf
  src:
    src: ../../../.build/scf/Benchmark
  runtime: CustomRuntime
  region: ap-beijing
  description: Swift SCF demo for benchmark
  handler: swift.main
  memorySize: 128
  timeout: 20
  initTimeout: 3