version: "3"

services:

  runtime-setup:
    image: swift-tencent-scf:scf-5.4.1
    build:
      args:
        swift_version: "5.4.1"

  test:
    image: swift-tencent-scf:scf-5.4.1

  test-samples:
    image: swift-tencent-scf:scf-5.4.1

  shell:
    image: swift-tencent-scf:scf-5.4.1
