# this file is not designed to be run directly
# instead, use the docker-compose.<os>.<swift> files
# eg docker-compose -f docker/docker-compose.yaml -f docker/docker-compose.scf.53.yaml run test
version: "3"

services:

  runtime-setup:
    image: swift-tencent-scf:default
    build:
      context: .
      dockerfile: Dockerfile

  common: &common
    image: swift-tencent-scf:default
    depends_on: [runtime-setup]
    volumes:
      - ~/.ssh:/root/.ssh
      - ..:/code:z
    working_dir: /code
    cap_drop:
      - CAP_NET_RAW
      - CAP_NET_BIND_SERVICE

  soundness:
    <<: *common
    command: /bin/bash -cl "./scripts/soundness.sh"

  test:
    <<: *common
    command: /bin/bash -cl "swift test --enable-test-discovery -Xswiftc -warnings-as-errors $${SANITIZER_ARG-}"

  test-samples:
    <<: *common
    command: >-
      /bin/bash -clx "
      swift build --package-path Examples/LambdaFunctions &&
      swift build --package-path Examples/LocalDebugging/MyLambda"

  # util

  shell:
    <<: *common
    entrypoint: /bin/bash
