component: scf
name: SwiftAPIGatewayDemo
inputs:
  name: apigateway-swift-scf
  src:
    src: ../../../.build/scf/APIGateway
  runtime: CustomRuntime
  region: ap-beijing
  description: Swift SCF demo for APIGateway
  handler: swift.main
  memorySize: 64
  timeout: 3
  initTimeout: 3
  events:
    - apigw:
        name: swift-scf-apigw
        parameters:
          protocols:
            - http
            - https
          serviceName: SwiftAPIGatewayDemo
          description: Swift SCF demo for APIGateway
          environment: release
          endpoints:
            - path: /api
              method: GET
              function:
                isIntegratedResponse: TRUE
